// automatically generated by the FlatBuffers compiler, do not modify

package Protocol

const (
	NuggetTypeUPDATE = 0
	NuggetTypeEVENT = 1
)

var EnumNamesNuggetType = map[int]string{
	NuggetTypeUPDATE:"UPDATE",
	NuggetTypeEVENT:"EVENT",
}

